root: true
parser: "@babel/eslint-parser"
parserOptions:
  requireConfigFile: false
extends:
  - "airbnb-base"
  - plugin:flowtype/recommended
plugins:
  - flowtype
rules:
  import/no-extraneous-dependencies: [2, {}]
  max-len: 0
  import/prefer-default-export: 0
