service: ig-images

frameworkVersion: ">=1.8.0"

provider:
  deploymentBucket: ${env:DEPLOYMENT_BUCKET}
  name: aws
  runtime: nodejs12.x
  stage: dev # just a default
  region: eu-west-1
  role: ${env:AWS_ROLE}
  environment:
    OBJECT_PREFIX: v1/
    IMAGE_BUCKET: ${env:IMAGES_BUCKET}
    OKTA_ISSUER: ${env:OKTA_ISSUER}
    OKTA_CLIENT_ID: ${env.OKTA_CLIENT_ID}

functions:
  list:
    handler: handler.list
    role: ${env:AWS_ROLE}
    events:
      - http:
          path: list
          method: get
          cors:
            origins:
              - '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
            allowCredentials: true

  get-upload-url:
    handler: handler.getUploadUrl
    role: ${env:AWS_ROLE}
    events:
      - http:
          path: get-upload-url
          method: get
          cors:
            origins:
              - '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
            allowCredentials: true
