version: 2
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: cimg/node:14.18
    steps:
      - checkout
      - restore_cache:
          key: project-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: npm ci
      - save_cache:
          key: project-{{ checksum "package-lock.json" }}
          paths:
            - node_modules/
      - run:
          name: ESLint
          command: npm run eslint -- .
      - run:
          name: Compile src -> dist
          command: npm run build
      - store_artifacts:
          path: dist/
      - deploy:
          name: Maybe deploy
          command: |
            if [ "${CIRCLE_BRANCH}" == "main" ]; then
              npm run deploy:prod
            fi
